apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: salomaopolegar/microsservico_pagamento
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: payments-configmap
        resources:
            requests:
              cpu: 400m
